=== uwitec/tig-panel-web/trunk/WebRoot/WEB-INF/classes/com/application/webserver/parameters/systemdictionary.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT system-dictionary-config (dictionary-item+)>

<!ELEMENT dictionary-item (item+)>
<!ATTLIST dictionary-item id        CDATA   #REQUIRED>
<!ATTLIST dictionary-item desc      CDATA   #REQUIRED>

<!ELEMENT item (value, value-description)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT value-description (#PCDATA)>

=== uwitec/tig-panel-web/trunk/src/com/application/webserver/parameters/systemdictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE system-dictionary-config PUBLIC "-//HUATENG//DTD System Dictionary DTD//EN" "http://www.huateng.com/Guatemala/systemdictionary.dtd">
<system-dictionary-config>
	<dictionary-item id="60007" desc="statueType">
		<item>
			<value>0</value>
			<value-description>dictionary.60007.statueType.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.60007.statueType.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.60007.statueType.2</value-description>
		</item>
		<item>
			<value>9</value>
			<value-description>dictionary.60007.statueType.9</value-description>
		</item>
	</dictionary-item>
	<dictionary-item id="10001" desc="rolestatus">
		<item>
			<value>1</value>
			<value-description>dictionary.10001.rolestatus.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.10001.rolestatus.2</value-description>
		</item>
	</dictionary-item>

	<dictionary-item id="10002" desc="gender">
		<item>
			<value>1</value>
			<value-description>dictionary.10002.gender.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.10002.gender.2</value-description>
		</item>
	</dictionary-item>


	<dictionary-item id="10003" desc="userstatus">
		<item>
			<value>1</value>
			
			<value-description>dictionary.10003.userstatus.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.10003.userstatus.2</value-description>
		</item>
	</dictionary-item>

	<dictionary-item id="10004" desc="usertype">
		<item>
			<value>1</value>
			<value-description>dictionary.10004.usertype.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.10004.usertype.2</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="10005" desc="usertype">
		<item>
			<value>0</value>
			<value-description>dictionary.10005.logflag.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.10005.logflag.1</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20001" desc="cardstate">
		<item>
			<value>0</value>
			<value-description>dictionary.20001.cardstate.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.20001.cardstate.1</value-description>
		</item>
		<item>
			<value>3</value>
			<value-description>dictionary.20001.cardstate.3</value-description>
		</item>
		<item>
			<value>9</value>
			<value-description>dictionary.20001.cardstate.9</value-description>
		</item>
		<item>
			<value>10</value>
			<value-description>dictionary.20001.cardstate.10</value-description>
		</item>
		<item>
			<value>11</value>
			<value-description>dictionary.20001.cardstate.11</value-description>
		</item>
		<item>
			<value>12</value>
			<value-description>dictionary.20001.cardstate.12</value-description>
		</item>
		<item>
			<value>13</value>
			<value-description>dictionary.20001.cardstate.13</value-description>
		</item>
		<item>
			<value>14</value>
			<value-description>dictionary.20001.cardstate.14</value-description>
		</item>
		<item>
			<value>15</value>
			<value-description>dictionary.20001.cardstate.15</value-description>
		</item>
		<item>
			<value>16</value>
			<value-description>dictionary.20001.cardstate.16</value-description>
		</item>
		<item>
			<value>21</value>
			<value-description>dictionary.20001.cardstate.21</value-description>
		</item>
		<item>
			<value>22</value>
			<value-description>dictionary.20001.cardstate.22</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20002" desc="crdphsctype">
		<item>
			<value>1</value>
			<value-description>dictionary.20002.crdphsctype.1</value-description>
		</item>
		<item>
			<value>3</value>
			<value-description>dictionary.20002.crdphsctype.3</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20003" desc="crdsalemode">
		<item>
			<value>0</value>
			<value-description>dictionary.20003.crdsalemode.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.20003.crdsalemode.1</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20004" desc="crdtestflag">
		<item>
			<value>0</value>
			<value-description>dictionary.20004.crdtestflag.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.20004.crdtestflag.1</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20005" desc="hylvl">
		<item>
			<value>1</value>
			<value-description>dictionary.20005.hylvl.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.20005.hylvl.2</value-description>
		</item>
		<item>
			<value>3</value>
			<value-description>dictionary.20005.hylvl.3</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20100" desc="crdacctype">
		<item>
			<value>1</value>
			<value-description>dictionary.20100.crdacctype.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.20100.crdacctype.2</value-description>
		</item>
		<item>
			<value>3</value>
			<value-description>dictionary.20100.crdacctype.3</value-description>
		</item>
		<item>
			<value>4</value>
			<value-description>dictionary.20100.crdacctype.4</value-description>
		</item>
		<item>
			<value>5</value>
			<value-description>dictionary.20100.crdacctype.5</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20101" desc="stptype">
		<item>
			<value>1</value>
			<value-description>dictionary.20101.stptype.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.20101.stptype.2</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20102" desc="stpattr">
		<item>
			<value>0</value>
			<value-description>dictionary.20102.stpattr.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.20102.stpattr.1</value-description>
		</item>
		<item>
			<value>9999</value>
			<value-description>dictionary.20102.stpattr.9999</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20103" desc="stpbusitype">
		<item>
			<value>1</value>
			<value-description>dictionary.20103.stpbusitype.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.20103.stpbusitype.2</value-description>
		</item>
		<item>
			<value>3</value>
			<value-description>dictionary.20103.stpbusitype.3</value-description>
		</item>
		<item>
			<value>4</value>
			<value-description>dictionary.20103.stpbusitype.4</value-description>
		</item>
		<item>
			<value>5</value>
			<value-description>dictionary.20103.stpbusitype.5</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20104" desc="stpstate">
		<item>
			<value>0</value>
			<value-description>dictionary.20104.stpstate.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.20104.stpstate.1</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20105" desc="stpconfirm">
		<item>
			<value>0</value>
			<value-description>dictionary.20105.stpconfirm.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.20105.stpconfirm.1</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20200" desc="disflag">
		<item>
			<value>0</value>
			<value-description>dictionary.20200.disflag.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.20200.disflag.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.20200.disflag.2</value-description>
		</item>
	</dictionary-item>	
	
	<dictionary-item id="20006" desc="unittype">
		<item>
			<value>0</value>
			<value-description>dictionary.20006.unittype.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.20006.unittype.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.20006.unittype.2</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20007" desc="unitstat">
		<item>
			<value>0</value>
			<value-description>dictionary.20007.unitstat.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.20007.unitstat.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.20007.unitstat.2</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20008" desc="unittestflag">
		<item>
			<value>0</value>
			<value-description>dictionary.20008.unittestflag.0</value-description>
		</item>
		<item>
			<value>1</value>
			<value-description>dictionary.20008.unittestflag.1</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20009" desc="unitlvl">
		<item>
			<value>1</value>
			<value-description>dictionary.20009.unitlvl.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.20009.unitlvl.2</value-description>
		</item>
		<item>
			<value>3</value>
			<value-description>dictionary.20009.unitlvl.3</value-description>
		</item>
	</dictionary-item>
	
	<dictionary-item id="20010" desc="nettype">
		<item>
			<value>1</value>
			<value-description>dictionary.20010.nettype.1</value-description>
		</item>
		<item>
			<value>2</value>
			<value-description>dictionary.20010.nettype.2</value-description>
		</item>
		<item>
			<value>3</value>
