=== uwitec/tig-panel-web/trunk/WebRoot/WEB-INF/classes/com/application/webserver/parameters/unitlevel.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT unit-level-config (unit-level+)>

<!ELEMENT unit-level (level, attribute-name)>
<!ATTLIST unit-level id        ID      #REQUIRED>
<!ATTLIST unit-level desc      CDATA   #REQUIRED>

<!ELEMENT level (#PCDATA)>
<!ELEMENT attribute-name (#PCDATA)>

=== uwitec/tig-panel-web/WebRoot/WEB-INF/classes/com/application/webserver/parameters/unitlevel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE unit-level-config PUBLIC "-//HUATENG//DTD Unit Level DTD//EN" "http://www.huateng.com/Guatemala/unitlevel.dtd" >
<unit-level-config>
	<unit-level id="DEVELOP" desc="Development Center">
		<level>0</level>
		<attribute-name>devcenter</attribute-name>
	</unit-level>

	<unit-level id="CC" desc="Card Center">
		<level>1</level>
		<attribute-name>cardcenter</attribute-name>
	</unit-level>

	<unit-level id="UNIT" desc="Unit">
		<level>2</level>
		<attribute-name>operationunit</attribute-name>
	</unit-level>

	<unit-level id="NET" desc="Network">
		<level>3</level>
		<attribute-name>operationnet</attribute-name>
	</unit-level>
</unit-level-config>
